### ISSUE TITLE
Can't build success on Ubuntu16.04

### ISSUE THREAD

**Issue by Cherisher** [wificoin-project/wificoin#4]
When I compile this project on Ubuntu16.04, There are some errors:
checking for boostlib >= 1.47.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Program_Options library is available... yes
configure: error: Could not link against boost_filesystem !

but, I have already install this library:
root@iZ2zehqe:/opt/wificoin_pool/wificoin# ls -al /usr/lib/x86_64-linux-gnu/libboost_filesystem.*
-rw-r--r-- 1 root root 234296 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.a
lrwxrwxrwx 1 root root     29 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so -> libboost_filesystem.so.1.58.0
-rw-r--r-- 1 root root  97064 Jun 14  2016 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0

**Comment by liudf0716** [comment]
did u apt-get install boost related library?
